apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      volumeMounts:
        - name: test-cm
          mountPath: /cm
      env:
        - name: SERVICE_B
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: app_ver
      envFrom:
        - configMapRef:
            name: fromenvfile
  volumes:
    - name: test-cm
      configMap:
        name: config1 
