apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: 'radial/busyboxplus:curl'
      name: busy
      command: ['sh', '-c', 'while true; do sleep 3600; done']
  restartPolicy: Never
