apiVersion: v1
kind: Pod
metadata:
  name: init-nginx-custom
spec: 
  initContainers:  
  - name: prepare
    image: busybox
    command: ['sh', '-c', 'echo "<html><h1>WELCOME FROM INIT CONTAINER</h1></html>" > /workdir/index.html']
    volumeMounts:
      - name: volume1
        mountPath: "/workdir"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: volume1
        mountPath: /usr/share/nginx/html
  volumes:
    - name: volume1
      emptyDir: {}

